### ISSUE TITLE
Issue on Chapter 4 LeaseContract.sol

### ISSUE THREAD

**Issue by hazrienne** [PacktPublishing/Learn-Ethereum#24]
Hello,

I'm getting this error when trying to compile LeaseContract.sol. Perhaps someone here encountered the same :

creation of LeaseContract errored: Error encoding arguments: Error: invalid BigNumber string (argument="value", value="", code=INVALID_ARGUMENT, version=bignumber/5.1.1)

Plus I'm getting this error on constructor field - Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.

**Comment by nithikpackt** [comment]
Hi @hazrienne , here's a reply from on the authors:

Here is what I found out:

1. The original code specifies to use solidity version between 0.5.0 and 0.7.0, it works fine under solidity version 0.5.x to version 0.7.x;
2. Reader reported error, "constructor field - Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient. “ is actually a warning. In remix environment, while compiling the code, such warning will be displayed. The compiled smart contract can be deployed and run under remix without any issues.
3. When changing the code to be compiled in solidity version 0.8.x, there are error regarding address to address payable conversion in line 45 of constructor code, lease.landlord = msg.sender. This is due to the solidity version difference. It can be fixed with the code: lease.landlord = payable(msg.sender); 
4. The same error is reported on line 99 for solidity version 0.8.x. It can be fixed with the code: lease.tenant = payable(msg.sender);
5. I have tried version from 0.5x all the way to 0.8.x, I didn’t run into any error like the reader reported, quoted here, "creation of LeaseContract errored: Error encoding arguments: Error: invalid BigNumber string (argument="value", value="", code=INVALID_ARGUMENT, version=bignumber/5.1.1)”. Maybe the reader can provide some more details.

Closing the issue for now.
